version: '3.8'

services:
  tg-service:
    build: .
    container_name: tg-listener
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./sessions:/app/sessions
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - PHONE_NUMBER=${PHONE_NUMBER}
      - HTTP_PORT=8080
      - TZ=Asia/Shanghai
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
